version: "3.9"

services:
  heimdall:
    image: linuxserver/heimdall:2.5.6
    container_name: heimdall
    networks:
      - proxy
    volumes:
      - /apps/heimdall/data:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.entrypoints=websecure
      - traefik.http.routers.heimdall.rule=Host(`heimdall.exemple.fr`)
    restart: always

networks:
  proxy:
    name: "proxy"
    external: true
